spring:
  config:
    import:
      - "classpath:config/bot.yml"
      - "classpath:config/database.yml"
      - "optional:file:./config/bot.yml"
      - "optional:file:./config/database.yml"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.weslaycodes.stockpile: INFO
    net.dv8tion.jda: WARN